import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Coworking from '../views/Coworking'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CoWork</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Coworking/>
    </div>
  )
}
